server:
  port: 8108
spring:
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8761/eureka
feign:
  compression:
    request:
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
