logging:
    level:
        tk.mybatis: DEBUG
spring:
    application:
        name: taxi-user
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/taxi-user?useUnicode=true&characterEncoding=UTF8
        username: root
        password: 123456
        # 使用Hikari数据源
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
    basepackage: com.yoogurt.taxi.**.dal.**.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: 8100
