server:
  port: 8100
spring:
  application:
    name: taxi-user
  redis:
      host: 192.168.0.222
      port: 6370
      password: taxi0
      timeout: 1800000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.168.0.222:3306/taxi-user?useUnicode=true&characterEncoding=UTF8
    username: root
    password: taxi123456
    # 使用Hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.111:10000/eureka
