server:
  port: 11111
spring:
  application:
    name: taxi-gateway
  redis:
      host: 192.168.0.222
      port: 6370
      password: '{cipher}24462190beaad45fc90fd249abfc16af0cc2c49530702a35036314f6d08de5ef'
      timeout: 1800000
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.168.0.222:3306/taxi-gateway?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: '{cipher}aaa598ab8836842c849b48b772f8fbfc48fef9c4fb9f933dbeb73b91128e1523'
    # 使用Hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://peer1:10000/eureka
feign:
  compression:
    request:
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
  httpclient:
    enabled: false
  okhttp:
    enabled: true
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    user:
      path: /*/user/**
      serviceId: taxi-user
    account:
      path: /*/account/**
      serviceId: taxi-account
    order:
      path: /*/order/**
      serviceId: taxi-order
    finance:
      path: /*/finance/**
      serviceId: taxi-finance
    notification:
      path: /*/notification/**
      serviceId: taxi-notification
    system:
      path: /*/system/**
      serviceId: taxi-system
taxi-user:
  ribbon:
    ReadTimeout: 12000
    ConnectTimeout: 12000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: true
    httpclient:
      enabled: false
    okhttp:
      enabled: true
  hystrix:
    threadpool:
      default:
        coreSize: 1000 ##并发执行的最大线程数，默认10
        maxQueueSize: 200 ##BlockingQueue的最大队列数
        queueSizeRejectionThreshold: 200 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            strategy: THREAD
            semaphore:
              maxConcurrentRequests: 1000
            thread:
              timeoutInMilliseconds: 30000
taxi-account:
  ribbon:
    ReadTimeout: 12000
    ConnectTimeout: 12000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: true
    httpclient:
      enabled: false
    okhttp:
      enabled: true
  hystrix:
    threadpool:
      default:
        coreSize: 1000 ##并发执行的最大线程数，默认10
        maxQueueSize: 200 ##BlockingQueue的最大队列数
        queueSizeRejectionThreshold: 200 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            strategy: THREAD
            semaphore:
              maxConcurrentRequests: 1000
            thread:
              timeoutInMilliseconds: 30000
taxi-order:
  ribbon:
    ReadTimeout: 13000
    ConnectTimeout: 13000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: true
    httpclient:
      enabled: false
    okhttp:
      enabled: true
  hystrix:
    threadpool:
      default:
        coreSize: 1000 ##并发执行的最大线程数，默认10
        maxQueueSize: 200 ##BlockingQueue的最大队列数
        queueSizeRejectionThreshold: 200 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            strategy: THREAD
            semaphore:
              maxConcurrentRequests: 1000
            thread:
              timeoutInMilliseconds: 30000
taxi-system:
  ribbon:
    ReadTimeout: 12000
    ConnectTimeout: 12000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: true
    httpclient:
      enabled: false
    okhttp:
      enabled: true
  hystrix:
    threadpool:
      default:
        coreSize: 1000 ##并发执行的最大线程数，默认10
        maxQueueSize: 200 ##BlockingQueue的最大队列数
        queueSizeRejectionThreshold: 200 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            strategy: THREAD
            semaphore:
              maxConcurrentRequests: 1000
            thread:
              timeoutInMilliseconds: 30000
taxi-finance:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: true
    httpclient:
      enabled: false
    okhttp:
      enabled: true
  hystrix:
    threadpool:
      default:
        coreSize: 1000 ##并发执行的最大线程数，默认10
        maxQueueSize: 200 ##BlockingQueue的最大队列数
        queueSizeRejectionThreshold: 200 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            strategy: THREAD
            semaphore:
              maxConcurrentRequests: 1000
            thread:
              timeoutInMilliseconds: 30000
taxi-notification:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: true
    httpclient:
      enabled: false
    okhttp:
      enabled: true
  hystrix:
    threadpool:
      default:
        coreSize: 1000 ##并发执行的最大线程数，默认10
        maxQueueSize: 200 ##BlockingQueue的最大队列数
        queueSizeRejectionThreshold: 200 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            strategy: THREAD
            semaphore:
              maxConcurrentRequests: 1000
            thread:
              timeoutInMilliseconds: 30000