server:
  port: 8103
spring:
  application:
    name: taxi-finance
  rabbitmq:
    host: 120.55.42.113
    port: 5672
    connection-timeout: 7000
    virtual-host: /
    username: root
    password: '{cipher}aaa598ab8836842c849b48b772f8fbfc48fef9c4fb9f933dbeb73b91128e1523'
    listener:
      simple:
        acknowledge-mode: auto
  redis:
      host: 120.55.42.113
      port: 6370
      password: '{cipher}24462190beaad45fc90fd249abfc16af0cc2c49530702a35036314f6d08de5ef'
      timeout: 1800000
  data:
    mongodb:
      host: 120.55.42.113
      port: 27334
      database: finance
      authenticationDatabase: finance
      username: finance
      password: '{cipher}fac45ada0f02cca623c7624449b0f086033ba7105257ddb4cc4c2b5741b3523a'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://rm-bp1cj68xrmcrqk78c.mysql.rds.aliyuncs.com:3306/taxi-finance?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: yoogurt
    password: '{cipher}2c7f1c5a93ef567cf5c643765fc19b1de03fce98b4006d8c77947bb5dd9db93b'
    # 使用Hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://peer1:10000/eureka
