server:
  port: 8101
spring:
  application:
    name: taxi-order
  rabbitmq:
    host: 120.55.42.113
    port: 5672
    connection-timeout: 7000
    virtual-host: /
    username: root
    password: taxi123456
  redis:
      host: 120.55.42.113
      port: 6370
      password: taxi0
      timeout: 1800000
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://rm-bp1cj68xrmcrqk78c.mysql.rds.aliyuncs.com:3306/taxi-order?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: taxi123456
    # 使用Hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://peer1:10000/eureka
