server:
  port: 11111
spring:
  application:
    name: taxi-gateway
  redis:
      host: 192.168.0.222
      port: 6370
      password: taxi0
      timeout: 1800000
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/taxi-gateway?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    # 使用Hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.111:10000/eureka
feign:
  compression:
    request:
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    user:
      path: /*/user/**
      serviceId: taxi-user
    account:
      path: /*/account/**
      serviceId: taxi-account
    order:
      path: /*/order/**
      serviceId: taxi-order
    finance:
      path: /*/finance/**
      serviceId: taxi-finance
    notification:
      path: /*/notification/**
      serviceId: taxi-notification
    system:
      path: /*/system/**
      serviceId: taxi-system
