server:
  port: 11111
spring:
  application:
    name: taxi-gateway
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth-center?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    # 使用Hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8761/eureka
feign:
  compression:
    request:
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
gateway:
  jwt:
    secret: taxi!@#
    expire_seconds: 100
    header: Authorization
zuul:
  routes:
    user:
      path: /*/user/**
      serviceId: taxi-user
    account:
      path: /*/account/**
      serviceId: taxi-account
    order:
      path: /*/order/**
      serviceId: taxi-order
    finance:
      path: /*/finance/**
      serviceId: taxi-finance
    notification:
      path: /*/notification/**
      serviceId: taxi-notification
    system:
      path: /*/system/**
      serviceId: taxi-system
