server:
  port: 8102
spring:
  application:
    name: taxi-account
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.168.0.222:3306/taxi-account?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: taxi123456
    # 使用Hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://peer1:10000/eureka
