server:
  port: 11111
spring:
  application:
    name: taxi-gateway
  redis:
      host: 120.55.42.113
      port: 6370
      password: taxi0
      timeout: 1800000
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://rm-bp1cj68xrmcrqk78c.mysql.rds.aliyuncs.com:3306/taxi-gateway?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: taxi123456
    # 使用Hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://peer1:10000/eureka
feign:
  compression:
    request:
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    user:
      path: /*/user/**
      serviceId: taxi-user
    account:
      path: /*/account/**
      serviceId: taxi-account
    order:
      path: /*/order/**
      serviceId: taxi-order
    finance:
      path: /*/finance/**
      serviceId: taxi-finance
    notification:
      path: /*/notification/**
      serviceId: taxi-notification
    system:
      path: /*/system/**
      serviceId: taxi-system
taxi-user:
  ribbon:
    ReadTimeout: 12000
    ConnectTimeout: 12000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: true
  hystrix:
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 15000
taxi-account:
  ribbon:
    ReadTimeout: 12000
    ConnectTimeout: 12000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: true
  hystrix:
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 15000
taxi-order:
  ribbon:
    ReadTimeout: 13000
    ConnectTimeout: 13000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: true
  hystrix:
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 15000
taxi-system:
  ribbon:
    ReadTimeout: 12000
    ConnectTimeout: 12000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: true
  hystrix:
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 15000
taxi-finance:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: true
  hystrix:
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 15000
taxi-notification:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: true
  hystrix:
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 15000
