server:
  port: 8102
spring:
  application:
    name: taxi-account
  rabbitmq:
    host: 116.62.201.147
    port: 5672
    connection-timeout: 7000
    virtual-host: /
    username: root
    password: '{cipher}aaa598ab8836842c849b48b772f8fbfc48fef9c4fb9f933dbeb73b91128e1523'
    listener:
      simple:
        acknowledge-mode: auto
  data:
    mongodb:
      host: 116.62.201.147
      port: 27334
      database: finance
      authenticationDatabase: finance
      username: finance
      password: '{cipher}fac45ada0f02cca623c7624449b0f086033ba7105257ddb4cc4c2b5741b3523a'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://rm-bp1350w364k2r6sz3.mysql.rds.aliyuncs.com/taxi-account?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: yoogurt
    password: '{cipher}593904d6330413cf8698804b46d964cc44be00cf7cd5d57c63c7ca96faadcc56'
    # 使用Hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://peer1:10000/eureka
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
