server:
  port: 11111
spring:
  application:
    name: taxi-gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true
  redis:
      host: 192.168.0.222
      port: 6370
      password: '{cipher}24462190beaad45fc90fd249abfc16af0cc2c49530702a35036314f6d08de5ef'
      timeout: 1800000
  rabbitmq:
    host: 192.168.0.222
    port: 5672
    connection-timeout: 7000
    virtual-host: /
    username: root
    password: '{cipher}aaa598ab8836842c849b48b772f8fbfc48fef9c4fb9f933dbeb73b91128e1523'
    listener:
      simple:
        acknowledge-mode: auto
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.168.0.222:3306/taxi-gateway?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: '{cipher}aaa598ab8836842c849b48b772f8fbfc48fef9c4fb9f933dbeb73b91128e1523'
    # 使用Hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://peer1:10000/eureka
feign:
  compression:
    request:
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
  hystrix:
    enabled: true
zuul:
  retryable: true
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 30000
    connect-timeout-millis: 30000
  routes:
    user:
      path: /*/user/**
      serviceId: taxi-user
    account:
      path: /*/account/**
      serviceId: taxi-account
    order:
      path: /*/order/**
      serviceId: taxi-order
    finance:
      path: /*/finance/**
      serviceId: taxi-finance
    notification:
      path: /*/notification/**
      serviceId: taxi-notification
    system:
      path: /*/system/**
      serviceId: taxi-system
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 1000
taxi-user:
  ribbon:
    ReadTimeout: 15000
    ConnectTimeout: 15000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
    eureka:
      enabled: true
taxi-account:
  ribbon:
    ReadTimeout: 15000
    ConnectTimeout: 15000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
    eureka:
      enabled: true
taxi-order:
  ribbon:
    ReadTimeout: 15000
    ConnectTimeout: 15000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
    eureka:
      enabled: true
taxi-system:
  ribbon:
    ReadTimeout: 15000
    ConnectTimeout: 15000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
    eureka:
      enabled: true
taxi-finance:
  ribbon:
    ReadTimeout: 15000
    ConnectTimeout: 15000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
    eureka:
      enabled: true
taxi-notification:
  ribbon:
    ReadTimeout: 15000
    ConnectTimeout: 15000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
    eureka:
      enabled: true
