server:
  port: 8100
spring:
  application:
    name: taxi-user
  redis:
      host: 120.55.42.113
      port: 6370
      password: taxi0
      timeout: 1800000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://rm-bp1cj68xrmcrqk78c.mysql.rds.aliyuncs.com:3306/taxi-user?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: yoogurt
    password: taxi123!@#
    # 使用Hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://peer1:10000/eureka
